# Generated by Django 5.1.2 on 2024-11-19 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('pedidos', '0003_alter_carritocompras_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='carritocompras',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='carritocompras',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='carritocompras',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carritos', to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='clientes.cliente'),
        ),
    ]
