# Generated by Django 5.1.2 on 2024-11-20 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('pedidos', '0004_alter_carritocompras_unique_together_and_more'),
        ('productos', '0004_producto_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='carritocompras',
            name='carrito',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='pedidos.carrito'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='carritocompras',
            unique_together={('carrito', 'producto')},
        ),
        migrations.RemoveField(
            model_name='carritocompras',
            name='cliente',
        ),
    ]
