# Generated by Django 5.1.2 on 2024-11-20 19:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_carrito_carritocompras_carrito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='cart_id',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True),
        ),
    ]
