# Generated by Django 5.1.4 on 2024-12-09 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
