# Generated by Django 5.1.3 on 2024-12-08 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_purchase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
