# Generated by Django 5.1.2 on 2024-11-15 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
        migrations.AddField(
            model_name='producto',
            name='imagenes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
