# Generated by Django 5.1.3 on 2024-11-30 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
