# Generated by Django 5.1.3 on 2024-12-04 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_alter_producto_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fecha_primer_procesamiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_ultima_modificacion_ia',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='procesado_por_ia',
            field=models.BooleanField(default=False),
        ),
    ]
