# Generated by Django 5.1.4 on 2024-12-06 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_producto_fecha_primer_procesamiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='calidad',
            field=models.CharField(choices=[('original', 'Original'), ('alternativo', 'Alternativo'), ('otras', 'Otras Referencias')], default='alternativo', max_length=20),
        ),
    ]
