# Generated by Django 5.1.4 on 2024-12-07 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_producto_calidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='calidad',
            field=models.CharField(choices=[('original', 'Original'), ('alternativo', 'Alternativo'), ('otras', 'Otras Referencias')], default='original', max_length=20),
        ),
    ]
