# Generated by Django 5.1.4 on 2024-12-08 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0012_producto_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventariosucursal',
            name='disponibilidad',
            field=models.BooleanField(default=True),
        ),
    ]
